import '../game_host.dart';
import 'balance.dart';
import 'biglittle.dart';
import 'breathe.dart';
import 'bubbles.dart';
import 'coloring.dart';
import 'compare.dart';
import 'counting.dart';
import 'creature.dart';
import 'differences.dart';
import 'dots.dart';
import 'dressup.dart';
import 'farm.dart';
import 'freeze.dart';
import 'hear.dart';
import 'hop.dart';
import 'hundred.dart';
import 'ispy.dart';
import 'jigsaw.dart';
import 'letters.dart';
import 'mazes.dart';
import 'memory.dart';
import 'monster.dart';
import 'music.dart';
import 'oddone.dart';
import 'paint.dart';
import 'patterns.dart';
import 'rhymes.dart';
import 'sequencer.dart';
import 'shadows.dart';
import 'shapes.dart';
import 'sight.dart';
import 'sizes.dart';
import 'spell.dart';
import 'stories.dart';
import 'sudoku.dart';
import 'tally.dart';
import 'tracing.dart';
import 'zoo.dart';

/// Every game's playfield, by game id (SPEC FR-TOY-02/03). The launcher
/// shows only games that have one.
final Map<String, GameBuilder> kGameBuilders = {
  'bubbles': BubbleGame.new,
  'music': MusicGame.new,
  'farm': FarmGame.new,
  'memory': MemoryGame.new,
  'shapes': ShapeGame.new,
  'counting': CountingGame.new,
  'monster': MonsterGame.new,
  'coloring': ColoringGame.new,
  'jigsaw': JigsawGame.new,
  'paint': PaintGame.new,
  'patterns': PatternsGame.new,
  'oddone': OddOneGame.new,
  'shadows': ShadowsGame.new,
  'sizes': SizesGame.new,
  'mazes': MazesGame.new,
  'stories': StoriesGame.new,
  'sudoku': SudokuGame.new,
  'differences': DifferencesGame.new,
  'letters': LettersGame.new,
  'rhymes': RhymesGame.new,
  'ispy': SpyGame.new,
  'tracing': TracingGame.new,
  'numbers': NumbersGame.new,
  'breathe': BreatheGame.new,
  'creature': CreatureGame.new,
  'dots': DotsGame.new,
  'biglittle': BigLittleGame.new,
  'hop': HopGame.new,
  'spell': SpellGame.new,
  'hear': HearGame.new,
  'sight': SightGame.new,
  'balance': BalanceGame.new,
  'compare': CompareGame.new,
  'zoo': ZooGame.new,
  'tally': TallyGame.new,
  'hundred': HundredGame.new,
  'freeze': FreezeGame.new,
  'sequencer': SequencerGame.new,
  'dressup': DressGame.new,
};
